promotionPolicies:
  - name: global
    policy:
      action: commit
  - name: guestbook
    selector:
      product:
        names: ['guestbook']
    policy:
      preAction: guestbook-pre-echo
  - name: guestbook-100
    priority: 100
    selector:
      product:
        names: ['guestbook']
    policy:
      preAction: guestbook-pre-echo-100
      postAction: non-prod-post-echo
  # - name: prod
  #   selector:
  #     targetEnvironment:
  #       types: ['PROD']
  #   policy:
  #     postAction: prod-post-echo
  # - name: non-prod
  #   selector:
  #     targetEnvironment:
  #       types: ['NON_PROD']
  #   policy:
  #     postAction: non-prod-post-echo