promotionPolicies:
  - name: global
    policy:
      action: commit
  - name: pr-restricted
    selector:
      targetEnvironment:
        names: ['pr-restricted']
    policy:
      action: commit
  - name: guestbook
    selector:
      product:
        names: ['guestbook']
    policy:
      preAction: guestbook-pre-echo
  - name: prod
    selector:
      targetEnvironment:
        types: ['PROD']
    policy:
      postAction: prod-post-echo
  - name: non-prod
    selector:
      targetEnvironment:
        types: ['NON_PROD']
    policy:
      postAction: non-prod-post-echo