promotionTemplate:
  name: guestbook
  matchLabels:
    app: guestbook

# create branches in deniscodefresh/argocd-example-apps
# cd /Users/melden/projects/tmp/argocd-example-apps; git checkout master; for branch in guestbook-{dev,pre-prod,prod}; do git checkout -b $branch; done; git push origin --all
applications:
  - name: guestbook-dev
    source:
      path: helm-guestbook
      repoURL: https://github.com/denis-codefresh/argocd-example-apps.git
      targetRevision: guestbook-dev
  - name: guestbook-pre-prod
    source:
      path: helm-guestbook
      repoURL: https://github.com/denis-codefresh/argocd-example-apps.git
      targetRevision: guestbook-pre-prod
  - name: guestbook-prod
    source:
      path: helm-guestbook
      repoURL: https://github.com/denis-codefresh/argocd-example-apps.git
      targetRevision: guestbook-prod