apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promotion-guestbook
  annotations:
    codefresh.io/app-group: test
spec:
  project: default
  destination:
    name: in-cluster
    namespace: codefresh
  source:
    path: charts/promotion-guestbook-helm
    repoURL: https://github.com/denis-codefresh/shared-git-source.git
    targetRevision: main
    helm:
      valueFiles:
        - values-override.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
