apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: {{ .Values.product.name }}
spec:
  promotionFlows:
    - name: {{ .Values.product.promotionFlow }}
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - promote-guestbook