apiVersion: codefresh.io/v1beta1
kind: PromotionTemplate
metadata:
  name: {{ .Values.promotionTemplate.name }}
spec:
  applicationSourceSelector:
    matchLabels:
{{- with .Values.promotionTemplate.matchLabels }}
{{ toYaml . | indent 6 }}
{{- end }}
  priority: 0
  versionSource:
    file: values.yaml
    jsonPath: $.image.tag
  promotion:
    values.yaml:
      jsonPaths:
        - $.image.tag
