apiVersion: codefresh.io/v1beta1
kind: PromotionTemplate
metadata:
  name: promotion-guestbook-helm
spec:
  applicationSourceSelector:
    matchLabels:
      codefresh.io/product: {{ .Values.product.name }}
  priority: 0
  versionSource:
    file: values.yaml
    jsonPath: $.image.tag
  promotion:
    values.yaml:
      jsonPaths:
        - $.image.tag
