apiVersion: csdp.codefresh.io/v1
kind: PromotionPolicy
metadata:
  name: env-prod-postaction-150
spec:
  priority: 150
  selector:
    targetEnvironment:
      types:
      - PROD
  policy:
    postAction: prod-post-checks