apiVersion: csdp.codefresh.io/v1
kind: PromotionPolicy
metadata:
  name: env-prod-postAction-150
spec:
  priority: 150
  selector:
    target:
      types:
      - PROD
  policy:
    postAction: prod-post-checks