apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-with-version-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    app: app-under-version-test
spec:
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/denis-codefresh/argocd-example-apps.git
    targetRevision: version-dev
  destination:
    name: in-cluster
    namespace: version-dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
