# apiVersion: codefresh.io/v1beta1
# kind: PromotionTemplate
# metadata:
#   name: app-config
#   labels:
#     app: app-under-version-test
# spec:
#   applicationSourceSelector:
#     matchLabels:
#       app: app-under-version-test
#   priority: 0
#   versionSource:
#     file: "values.yaml"
#     jsonPath: "{.image.tag}"
#   promotion:
#     values.yaml:
#       jsonPaths:
#         - $.image.tag